// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtm2bJpf49A72kzpi_VzexW9VgMXfDR4',
    appId: '1:1026492078800:web:e6fe8a0e878e357a29dcd5',
    messagingSenderId: '1026492078800',
    projectId: 'notes-5b5d8',
    authDomain: 'notes-5b5d8.firebaseapp.com',
    storageBucket: 'notes-5b5d8.appspot.com',
    measurementId: 'G-SP24HTEBC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCje7ortOmkZjSxBUX5noNpELkJSwUFgF4',
    appId: '1:1026492078800:android:1b215e9f6e551f7c29dcd5',
    messagingSenderId: '1026492078800',
    projectId: 'notes-5b5d8',
    storageBucket: 'notes-5b5d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsMvGtjFUPO5dezvqTTgtEru5NgeeF3z4',
    appId: '1:1026492078800:ios:bccd71126808516c29dcd5',
    messagingSenderId: '1026492078800',
    projectId: 'notes-5b5d8',
    storageBucket: 'notes-5b5d8.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsMvGtjFUPO5dezvqTTgtEru5NgeeF3z4',
    appId: '1:1026492078800:ios:bccd71126808516c29dcd5',
    messagingSenderId: '1026492078800',
    projectId: 'notes-5b5d8',
    storageBucket: 'notes-5b5d8.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATtm2bJpf49A72kzpi_VzexW9VgMXfDR4',
    appId: '1:1026492078800:web:20879aa5d91df17f29dcd5',
    messagingSenderId: '1026492078800',
    projectId: 'notes-5b5d8',
    authDomain: 'notes-5b5d8.firebaseapp.com',
    storageBucket: 'notes-5b5d8.appspot.com',
    measurementId: 'G-Q1RXGDF8PB',
  );
}
